### ISSUE TITLE
plugin stopped working

### ISSUE THREAD

**Issue by pcause** [muness/obsidian-ics#91] opened 2023-12-12 13:04 UTC
Everything was fine yesterday but today (2023-12-12) it stopped working.  Neither script or basic command work.  Opened the sandbox and only plugin installed there was ics and didn't work there.  Using MS365 calendar.

Note that I built a quickadd script to prompt for a date and then retrieve the items for that date (adding a task scheduled icon and date).  This worked yesterday and today return nothing.  The script is a variation of my previous quickadd script.  I added a console.log to log the tR value about to be returned and it was empty.  Hope that helps.

ADDED:  My events for today (but also yesterday)e all recurring.  I added a simple event.  Nothing.  I downloaded the ics file using the same URL as entered in the plugin.  I can see the simple event in the downloaded ics file.  I then did the command (not script) and nothing.

**Comment by muness** [comment] 2023-12-12 16:00
Thanks for the bug report, and sorry about the inconvenience, @pcause . :(

Strange, I tested 1.4.1 locally on my Windows machine and it's still working. No errors in the console?

**Comment by pcause** [comment] 2023-12-12 16:12
just run in sandbox on windows and saw this in console when running the command.  theme is sandbox is default

ICS: styles.css not found
plugin:ics:26 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'format')
    at Object.editorCallback (plugin:ics:26:263)
    at e.mobileOnly.Pt.isMobile.e.checkCallback (app.js:1:1761861)
    at xq (app.js:1:1761159)
    at t.onChooseItem (app.js:1:2363110)
    at t.onChooseSuggestion (app.js:1:1522724)
    at t.selectSuggestion (app.js:1:1522274)
    at e.useSelectedItem (app.js:1:1520555)
    at e.onSuggestionClick (app.js:1:1520291)
    at HTMLDivElement.s (enhance.js:1:10720)

**Comment by muness** [comment] 2023-12-12 16:56
Hmm, strange that started failing now, and apparently because of styling (which the plugin doesn't use). I'll double check to make sure that isn't a red herring.

Can you try replacing the `main.js` in your `<vault>/.obsidian/plugins/ics` with the `main-debug.js`  at https://github.com/muness/obsidian-ics/releases/download/1.4.1/main-debug.js ? With that, on desktop you can see the code that's failing and maybe send a screenshot?

Thanks!

**Comment by pcause** [comment] 2023-12-12 17:50
I downloaded, renamed the existing main.js to main.js.save and renamed this to main.js.  I run the command and see NOTHING in the console.

**Comment by muness** [comment] 2023-12-12 17:54
Sorry about all the trouble. I'll try creating a calendar on my O365 account with nothing but recurring events to see if I can duplicate the issue on my end.

**Comment by pcause** [comment] 2023-12-12 17:57
no trouble.  always happy to *try* to help.  i appreciate the plugin and your efforts!

**Comment by pcause** [comment] 2023-12-12 18:03
just uninstalled the plugin.  shutdown and restarted obsidian.  after restart installed the plugin, set my ics url.  I had deleted the old daily note before installing the plugin.  i created daily note.  no content but that ics: style.css not found message app.js:1 is in the console.

**Comment by pcause** [comment] 2023-12-13 12:28
I have another plugin, time-ruler, that reads the ics entry.  it also now can't read the calendar items.  it also uses the ical library as well, I think.  wonder if it is the library.  wget does get the ics file, so MS is making it availoable.  likely some issue with that library

**Comment by pcause** [comment] 2023-12-14 12:24
started working again.  i updates to the newest pre-release 15.2 yesterday and now works.  maybe that or ...????

**Comment by muness** [comment] 2023-12-15 13:25
> started working again. i updates to the newest pre-release 15.2 yesterday and now works. maybe that or ...????

Thanks for letting me know. Closing this out. Hopefully it was a bug in the ICS files that were being generated and MS now has a regression test to prevent it.

**Closed by muness** 2023-12-15 13:25 UTC
Labels: bug
