### ISSUE TITLE
Failed to load plugin

### ISSUE THREAD

**Issue by Fierce-Ninja** [muness/obsidian-ics#11] opened 2021-10-01 23:35 UTC
Steps I took to get the above error:
I downloaded the release, unzipped your file and saved all the files from that to the ics folder within the plugins folder, as instructed in your readme.  And then restarted the Obsidian app.  I searched and found ICS plugin.  Then I activated it. And I got the error "Failed to load plugin ics-plugin"

I am using Windows 10 on a PC.

**Comment by muness** [comment] 2021-10-02 11:36
I've tested in on Windows 10, Windows 11 and Mac OS. Can you see if there are any logs in the Developer Console when it loads? `Ctrl-Shift-i` should bring it up.

**Comment by tjroeder** [comment] 2021-10-05 15:12
I am having the same issue as well. Is there any prerequisite software that should be installed first? Currently running Obsidian v0.12.15. I am on macOS. Screenshot of the error below.

![Screenshot of the error](https://user-images.githubusercontent.com/78194232/135810065-92ee7949-f6f3-4914-b2c2-0662cd33d2f4.png)

Obsidian version:
![Obsidian version](https://user-images.githubusercontent.com/78194232/135810147-c12488d2-0153-4a7c-8bdd-dd77dddab19d.png)

I did not see anything of note, in the console. Though to be honest I am still pretty new to Mac so I don't exactly know what I am looking for. Thanks for the help.

**Comment by hbarudin** [comment] 2022-03-01 18:02
I think I got it to work: in addition to downloading and unzipping the `.zip`. file, you also need to download the `main.js` file in the release and drag it into the unzipped file as well.
<img width="264" alt="Screen Shot 2022-03-01 at 12 55 37 PM" src="https://user-images.githubusercontent.com/1155458/156223554-cff787c0-d04c-4c9d-8c30-b9e063199e76.png">

**Comment by fcwheat** [comment] 2022-04-03 18:18
@hbarudin suggestion worked for me. I also removed the [styles.css](https://github.com/muness/obsidian-ics/blob/master/styles.css) file because it wasn't clear why that was in the plugin and, not surprisingly given the style update in the file turned almost all text red.
![Obsidian_Help_-_Obsidian_v0_14_2](https://user-images.githubusercontent.com/5223653/161442240-012cf95f-77ef-42a9-b6b8-2bb2d2295bb7.png)

**Comment by fcwheat** [comment] 2022-04-04 01:39
Just realized that this was because I had downloaded the `Source code (zip)` file and was attempting to use that. If you download `obsidian-ics-0.9.10.zip` this works as expected.

**Comment by FetchFast** [comment] 2023-06-29 08:48
Could we put main.js into the zip file to help avoid this?

**Comment by muness** [comment] 2023-06-29 14:58
The issue is that folks are using the Source code zip instead of the release zip file as the [installation instructions] (https://github.com/muness/obsidian-ics#installation) state. 

Can y'all think of a way to clarify the instructions? 

Alternatively if I can fix the remaining recurring event bug, #36 , I can work on getting this into the Community Plugins list as I've yet to find a better alternative.

**Comment by muness** [comment] 2023-09-03 14:57
Closing now that the build has been stable and plugin is available through as an Obsidian Community Plugin

**Closed by muness** 2023-09-03 14:57 UTC
